// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnR5XVBaVeJBgdYyUhrPS4s5ovNBlAj9E',
    appId: '1:713136825390:web:4f76109b06b5e911bbebbf',
    messagingSenderId: '713136825390',
    projectId: 'chat-app-905bb',
    authDomain: 'chat-app-905bb.firebaseapp.com',
    storageBucket: 'chat-app-905bb.firebasestorage.app',
    measurementId: 'G-WFGEMQTYFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh3HtfrteV6LLkDDsq2QQELQGXjDWuXgA',
    appId: '1:713136825390:android:ef4a0392b7d4b002bbebbf',
    messagingSenderId: '713136825390',
    projectId: 'chat-app-905bb',
    storageBucket: 'chat-app-905bb.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnR5XVBaVeJBgdYyUhrPS4s5ovNBlAj9E',
    appId: '1:713136825390:web:733f7a38aabf821cbbebbf',
    messagingSenderId: '713136825390',
    projectId: 'chat-app-905bb',
    authDomain: 'chat-app-905bb.firebaseapp.com',
    storageBucket: 'chat-app-905bb.firebasestorage.app',
    measurementId: 'G-HG0XJYHV4P',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-pjDH30_ifKEQ61vOGCotKzXsS6DFchA',
    appId: '1:713136825390:ios:093bf3fc73585213bbebbf',
    messagingSenderId: '713136825390',
    projectId: 'chat-app-905bb',
    storageBucket: 'chat-app-905bb.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-pjDH30_ifKEQ61vOGCotKzXsS6DFchA',
    appId: '1:713136825390:ios:093bf3fc73585213bbebbf',
    messagingSenderId: '713136825390',
    projectId: 'chat-app-905bb',
    storageBucket: 'chat-app-905bb.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
